# Generated by Django 3.0.3 on 2020-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=600)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('category', models.CharField(choices=[('ns', 'NSFW'), ('ws', 'Wholesome'), ('sb', 'Sermon'), ('bb', 'Intelligent'), ('ha', 'Funny'), ('aw', 'Sad'), ('xx', 'Flagged')], max_length=40)),
            ],
        ),
    ]
