# Generated by Django 3.0.3 on 2020-02-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastas', '0004_auto_20200217_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='text',
            field=models.TextField(max_length=15000),
        ),
    ]
