# Generated by Django 3.0.3 on 2020-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastas', '0005_auto_20200217_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='category',
        ),
        migrations.AddField(
            model_name='pasta',
            name='categories',
            field=models.CharField(blank=True, choices=[('wholesome', 'wholesome'), ('sermon', 'sermon'), ('intelligent', 'intelligent'), ('dumb', 'dumb'), ('funny', 'funny'), ('sad', 'sad'), ('political', 'political'), ('complaint', 'complaint'), ('emoji', 'emoji'), ('daddy', 'daddy'), ('sexy', 'sexy'), ('pro', 'pro'), ('creepy', 'creepy'), ('food', 'food'), ('nsfw', 'nsfw')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pasta',
            name='long',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasta',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative')], default='', max_length=8),
        ),
    ]
