# Generated by Django 3.0.3 on 2020-05-10 02:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pastas', '0006_auto_20200509_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wholesome', 'wholesome'), ('sermon', 'sermon'), ('intelligent', 'intelligent'), ('dumb', 'dumb'), ('funny', 'funny'), ('sad', 'sad'), ('political', 'political'), ('complaint', 'complaint'), ('emoji', 'emoji'), ('daddy', 'daddy'), ('sexy', 'sexy'), ('pro', 'pro'), ('creepy', 'creepy'), ('food', 'food'), ('nsfw', 'nsfw')], default='', max_length=150),
        ),
    ]
