# Generated by Django 3.0.3 on 2020-08-28 18:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pastas', '0007_auto_20200509_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='long',
        ),
        migrations.AddField(
            model_name='pasta',
            name='clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pasta',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wholesome', 'wholesome'), ('sermon', 'sermon'), ('intelligent', 'intelligent'), ('dumb', 'dumb'), ('funny', 'funny'), ('sad', 'sad'), ('political', 'political'), ('complaint', 'complaint'), ('emoji', 'emoji'), ('daddy', 'daddy'), ('sexy', 'sexy'), ('pro', 'pro'), ('creepy', 'creepy'), ('food', 'food'), ('ascii-art', 'ascii-art'), ('story', 'story'), ('cyrillic', 'cyrillic'), ('chad', 'chad')], default='', max_length=150),
        ),
    ]
