version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=pp_base
      - POSTGRES_USER=pp_worker
      - POSTGRES_PASSWORD=safety2ndplacech@mp
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    environment: 
      - PROD=1
    build: .
    command: gunicorn pp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  pgdata:
    static_volume: